NHSDigital/eps-FHIR-validator-lambda

- .github/workflows/dependabot_auto_approve_and_merge.yml
- .github/workflows/pr-link.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- adds github workflows for the following
- release
- dependabot autoapprove and merge
- pr-link
> add github workflows

- src/main/java/software/nhs/FHIRValidator/HandlerStream.java
- src/main/java/software/nhs/FHIRValidator/Validator.java
> handle exception better

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- use INFO log level everywhere
> lower log levels

- .devcontainer/devcontainer.json
- README.md
- pom.xml
- src/main/java/software/nhs/FHIRValidator/Utils.java
- remove references to prescriptionsforpatients
> remove reference to prescriptionsforpatients

- .github/workflows/quality_checks.yml
- .github/workflows/sam_package_code.yml
- .tool-versions
- SAMtemplates/main_template.yaml
- pom.xml
> add sonar analysis

- .github/scripts/get_target_deployed_tag.sh
- use an initial tag if its not been deployed to an environment yet
> use initial tag if not deployed to an environment yet

- .github/workflows/ci.yml
- .github/workflows/release.yml
- remove extra space in github action files when outputting version
> Fix: [AEA-0000] - remove extra space in github action files

- .github/dependabot.yml
> Chore: [AEA-0000] - add npm to dependabot

- .github/workflows/ci.yml
- .github/workflows/release.yml
- add back in release to prod
- change name of SPEC_VERSION to VERSION_TAG in pipelines
> Chore: [AEA-0000] - enable release to prod

- .github/workflows/ci.yml
- fix next tag output in ci workflow
> Chore: [AEA-0000] - fix next tag output in ci workflow

- .github/workflows/sam_release_code.yml
- README.md
- use _deployments.csv file for deployment history rather than _releases.csv
> Chore: [AEA-0000] - change name used for file used for deployment history

- package.json
> Chore: [AEA-0000] - use full package.json

- .github/dependabot.yml
- fix title of pull requests for dependabot
> Chore: [AEA-0000] - fix dependabot title

- SAMtemplates/lambda_resources.yaml
- SAMtemplates/main_template.yaml
- Adds a lambda execution policy for the FHIR Validator
> Chore: [AEA-3831] - Add lambda execution policy

- SAMtemplates/lambda_resources.yaml
- SAMtemplates/main_template.yaml
- Tweaks lambdas execution policy export name
> Chore: [AEA-3831] - Tweaks lambdas execution policy export name

- src/main/java/software/nhs/fhirvalidator/handler/HandlerStream.java
> Fix: [AEA-0000] - correct logging

- .github/workflows/ci.yml
- package-lock.json
- package.json
- pin conventional-changelog-eslint as a dependency to stop it being auto updated
- fail ci build if it can not get tag
> Fix: [AEA-0000] - pin conventional-changelog-eslint and stop it updating automatically

- releaseNotesTemplates/commit.hbs
> Docs: [AEA-0000] - add release notes template

- SECURITY.md
> Docs: [AEA-4303] - update security.md

- .github/workflows/quality_checks.yml
- .gitignore
- Makefile
- README.md
- SAMtemplates/lambda_resources.yaml
- SAMtemplates/main_template.yaml
- scripts/run_cfn_guard.sh
> Fix: [AEA-4348] - set up cfn guard

- .gitallowed
- add cidr range for git secret
> Fix: [AEA-0000] - add cidr range for git secret
